import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/mode-toggle"
import "./globals.css";
import React from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Hayleys Chat Bot",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <SidebarProvider>
                {/*<AppSidebar />*/}
                <main className="flex flex-col h-screen w-full">
                    <header className="flex justify-between items-center p-2 border-b flex-shrink-0">
                        {/*<SidebarTrigger />*/}
                        <div className="flex-grow"></div>

                        <ModeToggle />
                    </header>
                    <div className="flex-1 overflow-auto p-4">
                        {children}
                    </div>
                </main>
            </SidebarProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}